"""add file_path

Revision ID: 4a03e406957f
Revises: adf3224450c5
Create Date: 2024-07-16 16:51:54.587568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a03e406957f'
down_revision: Union[str, None] = 'adf3224450c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_upload', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_upload', 'file_path')
    # ### end Alembic commands ###
